import { useEffect, useMemo, useState } from 'react'
import { Activity, ArrowDownRight, ArrowRight, ArrowUpRight, BarChart3, CalendarDays, Check, ChevronLeft, ChevronRight, CircleHelp, Clock3, CloudOff, Download, Globe2, LayoutDashboard, LogOut, Menu, MoreHorizontal, Plus, Search, Settings2, ShieldCheck, Spade, Tag, Trash2, UserRound, Users, Wallet, X } from 'lucide-react'
import type { User } from 'firebase/auth'
import { asYen, currencies, dateLabel, duration, fromMinor, hours, money, profit, samplePlayers, sampleSessions, shortDate, toMinor, type Currency, type Player, type Rate, type Session } from './domain'
import { deletePlayerRemote, deleteSessionRemote, firebaseConfigured, loadRemote, login, logout, savePlayerRemote, saveSessionRemote, watchUser } from './firebase'
import { getRate } from './rates'

type Page = 'overview' | 'sessions' | 'calendar' | 'analytics' | 'players' | 'settings'
const nav: { page: Page; label: string; icon: typeof LayoutDashboard }[] = [
  { page: 'overview', label: 'ダッシュボード', icon: LayoutDashboard },
  { page: 'sessions', label: 'セッション', icon: Spade },
  { page: 'calendar', label: 'カレンダー', icon: CalendarDays },
  { page: 'analytics', label: '収支分析', icon: BarChart3 },
  { page: 'players', label: 'プレイヤーメモ', icon: Users },
  { page: 'settings', label: '設定・データ', icon: Settings2 },
]
const title: Record<Page, string> = { overview: 'ダッシュボード', sessions: 'セッション', calendar: 'カレンダー', analytics: '収支分析', players: 'プレイヤーメモ', settings: '設定・データ' }
const readLocal = <T,>(key: string, fallback: T): T => { try { const value = localStorage.getItem(key); return value ? JSON.parse(value) as T : fallback } catch { return fallback } }
const today = () => new Date().toISOString().slice(0, 10)
const localInputDate = (date: Date) => new Date(date.getTime() - date.getTimezoneOffset() * 60_000).toISOString().slice(0, 16)
const formatYen = (value: number | null, signed = false) => value === null ? 'レート未取得' : money(value, 'JPY', signed)

function App() {
  const [page, setPage] = useState<Page>('overview')
  const [user, setUser] = useState<User | null>(null)
  const [authReady, setAuthReady] = useState(!firebaseConfigured)
  const [sessions, setSessions] = useState<Session[]>(() => readLocal('riverlog-demo-sessions', sampleSessions))
  const [players, setPlayers] = useState<Player[]>(() => readLocal('riverlog-demo-players', samplePlayers))
  const [rates, setRates] = useState<Partial<Record<Currency, Rate>>>({})
  const [sessionModal, setSessionModal] = useState<Session | 'new' | null>(null)
  const [playerModal, setPlayerModal] = useState<Player | 'new' | null>(null)
  const [selectedSession, setSelectedSession] = useState<Session | null>(null)
  const [sidebarOpen, setSidebarOpen] = useState(false)
  const [notice, setNotice] = useState('')
  const [now, setNow] = useState(Date.now())
  const [search, setSearch] = useState('')
  const [month, setMonth] = useState(() => new Date().getMonth())
  const [year, setYear] = useState(() => new Date().getFullYear())

  useEffect(() => { const id = window.setInterval(() => setNow(Date.now()), 60_000); return () => window.clearInterval(id) }, [])
  useEffect(() => { if (!firebaseConfigured) return; return watchUser(async next => {
    setUser(next); setAuthReady(true)
    if (next) {
      try { const data = await loadRemote(next.uid); setSessions(data.sessions); setPlayers(data.players) }
      catch { setNotice('データの読み込みに失敗しました。接続を確認してください。') }
    } else { setSessions(readLocal('riverlog-demo-sessions', sampleSessions)); setPlayers(readLocal('riverlog-demo-players', samplePlayers)) }
  }) }, [])
  useEffect(() => { if (!user) localStorage.setItem('riverlog-demo-sessions', JSON.stringify(sessions)) }, [sessions, user])
  useEffect(() => { if (!user) localStorage.setItem('riverlog-demo-players', JSON.stringify(players)) }, [players, user])
  useEffect(() => { const codes = [...new Set(sessions.map(s => s.currency).filter(c => c !== 'JPY'))]; codes.push('USD'); codes.forEach(code => getRate(code).then(rate => { if (rate) setRates(old => ({ ...old, [code]: rate })) })) }, [sessions.length])

  const sorted = useMemo(() => [...sessions].sort((a, b) => b.startedAt.localeCompare(a.startedAt)), [sessions])
  const completed = sorted.filter(s => s.endedAt)
  const active = sorted.find(s => !s.endedAt)
  const totalYen = completed.reduce((sum, s) => sum + (asYen(profit(s), s.currency, s.rate) || 0), 0)
  const totalHours = completed.reduce((sum, s) => sum + hours(s), 0)
  const wins = completed.filter(s => profit(s) > 0).length
  const liveRate = rates.USD

  const saveSession = async (session: Session) => {
    const previous = sessions
    setSessions(current => [session, ...current.filter(s => s.id !== session.id)])
    setSessionModal(null); setSelectedSession(null)
    if (user) try { await saveSessionRemote(user.uid, session) } catch { setSessions(previous); setNotice('保存に失敗しました。接続を確認してください。') }
    else setNotice('端末内のデモデータに保存しました')
  }
  const removeSession = async (id: string) => {
    if (!window.confirm('このセッションを削除しますか？')) return
    const previous = sessions; setSessions(current => current.filter(s => s.id !== id)); setSelectedSession(null)
    if (user) try { await deleteSessionRemote(user.uid, id) } catch { setSessions(previous); setNotice('削除に失敗しました') }
  }
  const savePlayer = async (player: Player) => {
    const previous = players; setPlayers(current => [player, ...current.filter(p => p.id !== player.id)]); setPlayerModal(null)
    if (user) try { await savePlayerRemote(user.uid, player) } catch { setPlayers(previous); setNotice('保存に失敗しました') }
    else setNotice('端末内のデモデータに保存しました')
  }
  const removePlayer = async (id: string) => {
    if (!window.confirm('このプレイヤーメモを削除しますか？')) return
    const previous = players; setPlayers(current => current.filter(p => p.id !== id)); setPlayerModal(null)
    if (user) try { await deletePlayerRemote(user.uid, id) } catch { setPlayers(previous); setNotice('削除に失敗しました') }
  }
  const navigate = (destination: Page) => { setPage(destination); setSidebarOpen(false); window.scrollTo(0, 0) }
  const exportCsv = () => {
    const rows = [['id','venue','location','game','stakes','currency','startedAt','endedAt','buyIn','rebuy','cashOut','tips','profit','rate','rateDate','note'], ...sessions.map(s => [s.id,s.venue,s.location,s.game,s.stakes,s.currency,s.startedAt,s.endedAt || '',fromMinor(s.buyIn,s.currency),fromMinor(s.rebuy,s.currency),fromMinor(s.cashOut,s.currency),fromMinor(s.tips,s.currency),fromMinor(profit(s),s.currency),s.rate?.rate || '',s.rate?.date || '',s.note])]
    const csv = '\ufeff' + rows.map(row => row.map(value => `"${String(value).replaceAll('"','""')}"`).join(',')).join('\r\n')
    const url = URL.createObjectURL(new Blob([csv], { type: 'text/csv;charset=utf-8' })); const a = document.createElement('a'); a.href = url; a.download = `riverlog-sessions-${today()}.csv`; a.click(); URL.revokeObjectURL(url)
  }

  return <div className="app-shell">
    {sidebarOpen && <button className="mobile-scrim" onClick={() => setSidebarOpen(false)} aria-label="メニューを閉じる" />}
    <aside className={`sidebar ${sidebarOpen ? 'open' : ''}`}>
      <div className="brand"><div className="brand-mark">R<span>●</span></div><div><strong>RIVERLOG</strong><small>POKER TRAVEL JOURNAL</small></div></div>
      <div className="workspace-label">WORKSPACE</div>
      <nav className="nav-list" aria-label="メインメニュー">{nav.map(item => <button key={item.page} className={`nav-item ${page === item.page ? 'active' : ''}`} onClick={() => navigate(item.page)}><item.icon size={19} strokeWidth={1.9} /><span>{item.label}</span>{page === item.page && <span className="nav-active-dot" />}</button>)}</nav>
      <div className="sidebar-bottom"><div className="sidebar-rate"><div className="sidebar-rate-heading"><Globe2 size={16} /> TODAY'S RATE</div><strong>1 USD <span>=</span> {liveRate ? `¥${liveRate.rate.toFixed(2)}` : '—'}</strong><small>{liveRate ? `${liveRate.date} 基準 · 参考レート` : 'レートを取得中'}</small></div><div className="sidebar-footer">{user ? <button onClick={() => logout()}><LogOut size={15} /> ログアウト</button> : <span><ShieldCheck size={15} /> {firebaseConfigured ? '閲覧用デモ' : 'ローカルデモモード'}</span>}</div></div>
    </aside>

    <main className="main">
      <header className="topbar"><div className="topbar-left"><button className="icon-button menu-button" onClick={() => setSidebarOpen(true)} aria-label="メニューを開く"><Menu size={22} /></button><span className="breadcrumb">RIVERLOG</span><ChevronRight size={15} className="breadcrumb-chevron" /><strong>{title[page]}</strong></div><div className="topbar-right"><div className="live-pill"><span className="pulse" /> {navigator.onLine ? 'SYNC READY' : 'OFFLINE'}</div><div className="topbar-avatar">{user?.photoURL ? <img src={user.photoURL} alt="" /> : <UserRound size={17} />}</div></div></header>
      <div className="content">
        {notice && <div className="notice" role="status">{notice}<button onClick={() => setNotice('')} aria-label="閉じる"><X size={16} /></button></div>}
        {!user && <div className="demo-banner"><div><ShieldCheck size={17} /><span>{firebaseConfigured ? 'デモを表示中。Google でログインすると自分のデータを保存できます。' : 'デモモードです。Firebase 設定後、Google ログインとクラウド同期が使えます。'}</span></div>{firebaseConfigured && authReady && <button onClick={() => login().catch(() => setNotice('ログインできませんでした。承認済みドメインを確認してください。'))}>Google でログイン <ArrowRight size={15} /></button>}</div>}

        {page === 'overview' && <>
          <div className="page-heading"><div><div className="eyebrow">OVERVIEW / {new Intl.DateTimeFormat('ja-JP', { year: 'numeric', month: 'long' }).format(new Date())}</div><h1>おかえりなさい<span className="title-period">.</span></h1><p>プレーと収支を、旅の流れに沿って振り返る。</p></div><button className="primary-button" onClick={() => setSessionModal('new')}><Plus size={18} /> セッションを記録</button></div>
          <section className="hero-grid"><div className="hero-card"><div className="hero-card-top"><span><Activity size={16} /> TOTAL PERFORMANCE</span><MoreHorizontal size={22} /></div><div className="hero-main"><div className="hero-overline">累計参考収支 <span>JPY 換算</span></div><div className="hero-amount">{money(totalYen, 'JPY', true)}</div><div className="hero-hint">終了済み {completed.length} セッションの固定レート換算</div></div><div className="hero-card-bottom"><span><span className="hero-dot" /> あなたの記録</span><span>01 / 03</span></div></div><div className="stat-stack"><StatCard icon={Clock3} label="総プレー時間" value={`${totalHours.toFixed(1)}h`} detail="終了済みセッション" /><StatCard icon={Wallet} label="平均時給" value={totalHours >= 0.05 ? formatYen(Math.round(totalYen / totalHours)) : '—'} detail="参考円換算 / 時間" /></div></section>
          <section className="insight-row"><div className="mini-stat"><div className="mini-icon green"><ArrowUpRight size={19} /></div><div><small>勝率</small><strong>{completed.length ? `${Math.round(wins / completed.length * 100)}%` : '—'}</strong></div><span>WIN RATE</span></div><div className="mini-stat"><div className="mini-icon amber"><Spade size={19} /></div><div><small>記録したセッション</small><strong>{sessions.length}回</strong></div><span>SESSIONS</span></div><div className="mini-stat"><div className="mini-icon blue"><Globe2 size={19} /></div><div><small>使用した通貨</small><strong>{new Set(sessions.map(s => s.currency)).size}種類</strong></div><span>CURRENCIES</span></div></section>
          {active && <section className="active-session"><div><span className="active-label"><span className="pulse" /> 進行中のセッション</span><h3>{active.venue} <span>{active.stakes}</span></h3><p>{duration(active, now)} プレー中 · {money(active.buyIn + active.rebuy, active.currency)} 投入</p></div><button className="secondary-button" onClick={() => setSelectedSession(active)}>セッションを開く <ArrowRight size={17} /></button></section>}
          <section className="section"><SectionHeading label="RECENT ACTIVITY" title="最近のセッション" action="すべて見る" onAction={() => navigate('sessions')} /><div className="session-list">{sorted.slice(0, 4).map(s => <SessionRow key={s.id} session={s} onClick={() => setSelectedSession(s)} />)}{!sorted.length && <Empty message="まだセッションがありません。最初の記録を作成しましょう。" />}</div></section>
          <div className="lower-grid"><section className="panel"><SectionHeading label="CURRENCY NOTE" title="円換算について" /><div className="rate-panel"><div className="rate-icon"><Globe2 size={23} /></div><div><strong>{liveRate ? `1 USD ≈ ¥${liveRate.rate.toFixed(2)}` : '参考レートを取得できませんでした'}</strong><p>{liveRate ? `${liveRate.date} 基準 · Frankfurter の日次参考レート` : '現地通貨の記録は引き続き利用できます。'}</p></div></div><p className="panel-note">記録時のレートを固定保存します。実際の両替・決済レートとは異なります。</p></section><section className="panel"><SectionHeading label="QUICK ACCESS" title="次の記録へ" /><button className="quick-link" onClick={() => setPlayerModal('new')}><span className="quick-icon"><Users size={20} /></span><span><strong>プレイヤーメモを追加</strong><small>卓で気づいた特徴を忘れずに</small></span><ArrowRight size={18} /></button><button className="quick-link" onClick={() => navigate('calendar')}><span className="quick-icon"><CalendarDays size={20} /></span><span><strong>カレンダーを開く</strong><small>旅のプレー履歴を日付で探す</small></span><ArrowRight size={18} /></button></section></div>
        </>}

        {page === 'sessions' && <><div className="page-heading"><div><div className="eyebrow">YOUR PLAY HISTORY</div><h1>セッション<span className="title-period">.</span></h1><p>現地通貨と円換算、両方の視点で記録する。</p></div><button className="primary-button" onClick={() => setSessionModal('new')}><Plus size={18} /> 新しいセッション</button></div><div className="filter-bar"><div className="search-box"><Search size={18} /><input placeholder="会場・ゲームで検索" value={search} onChange={e => setSearch(e.target.value)} /></div><span>{sorted.length} 件の記録</span></div><div className="session-list page-list">{sorted.filter(s => `${s.venue} ${s.game} ${s.location}`.toLowerCase().includes(search.toLowerCase())).map(s => <SessionRow key={s.id} session={s} onClick={() => setSelectedSession(s)} />)}{!sessions.length && <Empty message="まだセッションがありません。" />}</div></>}

        {page === 'calendar' && <><div className="page-heading"><div><div className="eyebrow">PLAY CALENDAR</div><h1>カレンダー<span className="title-period">.</span></h1><p>いつ、どこで、どれくらいプレーしたか。</p></div><button className="primary-button" onClick={() => setSessionModal('new')}><Plus size={18} /> 記録する</button></div><div className="calendar-panel"><div className="calendar-head"><h2>{year}年 {month + 1}月</h2><div><button className="icon-button" onClick={() => { const d = new Date(year, month - 1); setYear(d.getFullYear()); setMonth(d.getMonth()) }} aria-label="前月"><ChevronLeft size={20} /></button><button className="icon-button" onClick={() => { const d = new Date(year, month + 1); setYear(d.getFullYear()); setMonth(d.getMonth()) }} aria-label="翌月"><ChevronRight size={20} /></button></div></div><div className="calendar-grid">{['日','月','火','水','木','金','土'].map(day => <div className="calendar-weekday" key={day}>{day}</div>)}{Array.from({ length: new Date(year, month, 1).getDay() }, (_, i) => <div key={`blank-${i}`} />)}{Array.from({ length: new Date(year, month + 1, 0).getDate() }, (_, i) => { const day = i + 1; const matches = sorted.filter(s => { const d = new Date((s.localDate || s.startedAt.slice(0, 10)) + 'T12:00:00'); return d.getFullYear() === year && d.getMonth() === month && d.getDate() === day }); const result = matches.reduce((sum, s) => sum + (s.endedAt ? asYen(profit(s), s.currency, s.rate) || 0 : 0), 0); return <button key={day} className={`calendar-day ${matches.length ? 'has-session' : ''} ${new Date().getDate() === day && new Date().getMonth() === month && new Date().getFullYear() === year ? 'today' : ''}`} onClick={() => matches[0] && setSelectedSession(matches[0])}><span>{day}</span>{matches.length > 0 && <><i className={result < 0 ? 'loss' : ''} /><small>{matches.length}件</small></>}</button> })}</div></div><section className="section"><SectionHeading label="THIS MONTH" title="今月のセッション" /><div className="session-list">{sorted.filter(s => { const d = new Date((s.localDate || s.startedAt.slice(0, 10)) + 'T12:00:00'); return d.getFullYear() === year && d.getMonth() === month }).map(s => <SessionRow key={s.id} session={s} onClick={() => setSelectedSession(s)} />)}</div></section></>}

        {page === 'analytics' && <><div className="page-heading"><div><div className="eyebrow">PERFORMANCE INSIGHTS</div><h1>収支分析<span className="title-period">.</span></h1><p>数字から、自分のプレーを見つめ直す。</p></div></div><div className="analytics-grid"><StatCard icon={Wallet} label="累計参考収支" value={money(totalYen, 'JPY', true)} detail="記録時レートで円換算" /><StatCard icon={Clock3} label="総プレー時間" value={`${totalHours.toFixed(1)}h`} detail="終了済みセッション" /><StatCard icon={ArrowUpRight} label="勝率" value={completed.length ? `${Math.round(wins / completed.length * 100)}%` : '—'} detail={`${wins}勝 / ${completed.length}回`} /></div><div className="lower-grid"><section className="panel"><SectionHeading label="BY VENUE" title="会場別の収支" /><div className="bars">{Object.entries(completed.reduce<Record<string, Session[]>>((map, session) => { (map[session.venue] ||= []).push(session); return map }, {})).map(([venue, items]) => { const sum = items.reduce((acc, s) => acc + (asYen(profit(s), s.currency, s.rate) || 0), 0); const max = Math.max(1, ...completed.map(s => Math.abs(asYen(profit(s), s.currency, s.rate) || 0))); return <div className="bar-row" key={venue}><div><strong>{venue}</strong><span className={sum < 0 ? 'negative' : 'positive'}>{money(sum, 'JPY', true)}</span></div><div className="bar-track"><div className={sum < 0 ? 'bar-fill loss' : 'bar-fill'} style={{ width: `${Math.max(4, Math.min(100, Math.abs(sum) / max * 100))}%` }} /></div></div> })}{!completed.length && <Empty message="分析するセッションがありません。" />}</div></section><section className="panel"><SectionHeading label="HOW WE CALCULATE" title="集計の基準" /><div className="calc-note"><CircleHelp size={20} /><p>現地通貨の損益は「キャッシュアウト − バイイン − リバイ − チップ」で計算します。異なる通貨の合算には、各セッションに保存した日次参考レートを使います。為替の実現損益ではありません。</p></div></section></div></>}

        {page === 'players' && <><div className="page-heading"><div><div className="eyebrow">TABLE INTELLIGENCE</div><h1>プレイヤーメモ<span className="title-period">.</span></h1><p>次に同じ卓に座ったとき、思い出せるように。</p></div><button className="primary-button" onClick={() => setPlayerModal('new')}><Plus size={18} /> メモを追加</button></div><div className="filter-bar"><div className="search-box"><Search size={18} /><input placeholder="名前・会場・タグで検索" value={search} onChange={e => setSearch(e.target.value)} /></div><span>{players.length} 人のメモ</span></div><div className="player-grid">{players.filter(p => `${p.name} ${p.venue} ${p.tags.join(' ')} ${p.note}`.toLowerCase().includes(search.toLowerCase())).map(p => <button className="player-card" key={p.id} onClick={() => setPlayerModal(p)}><div className="player-card-top"><div className="player-avatar">{p.name.slice(0, 1).toUpperCase()}</div><MoreHorizontal size={21} /></div><h3>{p.name}</h3><p><Globe2 size={14} /> {p.venue || '会場未設定'}</p><div className="tags">{p.tags.map(tag => <span key={tag}>{tag}</span>)}</div><div className="player-note">{p.note || 'メモはまだありません'}</div><small>更新 {shortDate(p.updatedAt)}</small></button>)}{!players.length && <Empty message="プレイヤーメモがありません。" />}</div></>}

        {page === 'settings' && <><div className="page-heading"><div><div className="eyebrow">PREFERENCES & DATA</div><h1>設定・データ<span className="title-period">.</span></h1><p>記録を自分の手元でも管理する。</p></div></div><div className="settings-grid"><section className="panel"><SectionHeading label="ACCOUNT" title="アカウント" /><div className="setting-row"><div className="setting-icon"><UserRound size={20} /></div><div><strong>{user?.displayName || 'デモモード'}</strong><small>{user?.email || 'この端末のブラウザにデータを保存中'}</small></div></div>{firebaseConfigured && !user && <button className="secondary-button wide" onClick={() => login().catch(() => setNotice('ログインできませんでした'))}>Google でログイン <ArrowRight size={16} /></button>}{user && <button className="secondary-button wide" onClick={logout}>ログアウト <LogOut size={16} /></button>}</section><section className="panel"><SectionHeading label="YOUR DATA" title="データの持ち出し" /><p className="settings-description">すべてのセッションを CSV でダウンロードできます。データにはメモも含まれます。</p><button className="secondary-button wide" onClick={exportCsv}><Download size={17} /> CSV をダウンロード</button></section><section className="panel"><SectionHeading label="CURRENCY" title="為替データ" /><div className="setting-row"><div className="setting-icon"><Globe2 size={20} /></div><div><strong>Frankfurter 日次参考レート</strong><small>基準表示通貨: JPY · 実際の両替レートとは異なります</small></div></div><a className="text-link" href="https://frankfurter.dev/" target="_blank" rel="noreferrer">データ提供元を見る <ArrowRight size={15} /></a></section><section className="panel"><SectionHeading label="PRIVACY" title="プライバシー" /><div className="setting-row"><div className="setting-icon"><CloudOff size={20} /></div><div><strong>{user ? 'Firestore に保存' : 'この端末に保存'}</strong><small>プレイヤーメモは公開されません。画像の保存は行いません。</small></div></div></section></div></>}
      </div>
    </main>
    <nav className="mobile-nav" aria-label="モバイルメニュー">{nav.slice(0, 5).map(item => <button key={item.page} className={page === item.page ? 'active' : ''} onClick={() => navigate(item.page)}><item.icon size={21} /><span>{item.page === 'overview' ? 'ホーム' : item.page === 'players' ? 'メモ' : item.label}</span></button>)}</nav>
    {sessionModal && <SessionForm initial={sessionModal === 'new' ? undefined : sessionModal} rate={rates} onClose={() => setSessionModal(null)} onSave={saveSession} />}
    {playerModal && <PlayerForm initial={playerModal === 'new' ? undefined : playerModal} onClose={() => setPlayerModal(null)} onSave={savePlayer} onDelete={removePlayer} />}
    {selectedSession && <SessionDetail session={selectedSession} currentRate={rates[selectedSession.currency]} now={now} onClose={() => setSelectedSession(null)} onEdit={() => { setSessionModal(selectedSession); setSelectedSession(null) }} onDelete={() => removeSession(selectedSession.id)} onFinish={() => { setSessionModal(selectedSession); setSelectedSession(null) }} />}
  </div>
}

function StatCard({ icon: Icon, label, value, detail }: { icon: typeof Clock3; label: string; value: string; detail: string }) { return <div className="stat-card"><div className="stat-head"><div className="stat-icon"><Icon size={19} /></div><ArrowUpRight size={17} /></div><small>{label}</small><strong>{value}</strong><span>{detail}</span></div> }
function SectionHeading({ label, title, action, onAction }: { label: string; title: string; action?: string; onAction?: () => void }) { return <div className="section-heading"><div><div className="eyebrow">{label}</div><h2>{title}</h2></div>{action && <button className="text-link" onClick={onAction}>{action} <ArrowRight size={16} /></button>}</div> }
function Empty({ message }: { message: string }) { return <div className="empty"><Spade size={27} /><p>{message}</p></div> }
function SessionRow({ session, onClick }: { session: Session; onClick: () => void }) { const result = profit(session); const yen = asYen(result, session.currency, session.rate); return <button className="session-row" onClick={onClick}><div className={`result-icon ${!session.endedAt ? 'running' : result < 0 ? 'loss' : ''}`}>{!session.endedAt ? <Clock3 size={19} /> : result < 0 ? <ArrowDownRight size={20} /> : <ArrowUpRight size={20} />}</div><div className="session-main"><strong>{session.venue}</strong><span>{session.stakes} <span className="separator">·</span> {dateLabel((session.localDate || session.startedAt.slice(0, 10)) + 'T12:00:00')}</span></div><div className="session-extra"><span>{session.game}</span><small>{session.endedAt ? duration(session) : '進行中'}</small></div><div className={`session-result ${result < 0 ? 'negative' : 'positive'}`}><strong>{session.endedAt ? money(result, session.currency, true) : '進行中'}</strong><small>{session.endedAt ? formatYen(yen, true) : 'タップして開く'}</small></div><ChevronRight size={17} className="row-chevron" /></button> }

function SessionForm({ initial, rate, onClose, onSave }: { initial?: Session; rate: Partial<Record<Currency, Rate>>; onClose: () => void; onSave: (session: Session) => void }) {
  const [venue, setVenue] = useState(initial?.venue || '')
  const [location, setLocation] = useState(initial?.location || '')
  const [game, setGame] = useState<'ライブ' | 'オンライン'>(initial?.game || 'ライブ')
  const [stakes, setStakes] = useState(initial?.stakes || '')
  const [currency, setCurrency] = useState<Currency>(initial?.currency || 'USD')
  const [buyIn, setBuyIn] = useState(initial ? String(fromMinor(initial.buyIn, initial.currency)) : '')
  const [rebuy, setRebuy] = useState(initial ? String(fromMinor(initial.rebuy, initial.currency)) : '0')
  const [cashOut, setCashOut] = useState(initial ? String(fromMinor(initial.cashOut, initial.currency)) : '')
  const [tips, setTips] = useState(initial ? String(fromMinor(initial.tips, initial.currency)) : '0')
  const [note, setNote] = useState(initial?.note || '')
  const [finish, setFinish] = useState(Boolean(initial?.endedAt))
  const [startedAt, setStartedAt] = useState(initial ? localInputDate(new Date(initial.startedAt)) : localInputDate(new Date()))
  const submit = (event: React.FormEvent) => { event.preventDefault(); if (!venue.trim() || !buyIn) return; const now = new Date().toISOString(); onSave({ id: initial?.id || crypto.randomUUID(), venue: venue.trim(), location: location.trim(), game, stakes: stakes.trim(), currency, startedAt: new Date(startedAt).toISOString(), localDate: startedAt.slice(0, 10), endedAt: finish ? initial?.endedAt || now : undefined, buyIn: toMinor(Number(buyIn), currency), rebuy: toMinor(Number(rebuy || 0), currency), cashOut: toMinor(Number(cashOut || 0), currency), tips: toMinor(Number(tips || 0), currency), note: note.trim(), rate: finish ? initial?.rate || rate[currency] : initial?.rate, createdAt: initial?.createdAt || now, updatedAt: now }) }
  return <div className="modal-backdrop" onMouseDown={onClose}><div className="modal" onMouseDown={e => e.stopPropagation()} role="dialog" aria-modal="true" aria-label={initial ? 'セッションを編集' : '新しいセッション'}><div className="modal-header"><div><div className="eyebrow">SESSION ENTRY</div><h2>{initial ? 'セッションを編集' : '新しいセッション'}</h2></div><button className="icon-button" onClick={onClose} aria-label="閉じる"><X size={21} /></button></div><form onSubmit={submit}><div className="form-grid"><label className="field">会場名 <input required value={venue} onChange={e => setVenue(e.target.value)} placeholder="例: Bellagio" /></label><label className="field">都市 / 場所 <input value={location} onChange={e => setLocation(e.target.value)} placeholder="例: Las Vegas" /></label><label className="field">ゲーム <select value={game} onChange={e => setGame(e.target.value as 'ライブ' | 'オンライン')}><option>ライブ</option><option>オンライン</option></select></label><label className="field">ステークス <input value={stakes} onChange={e => setStakes(e.target.value)} placeholder="例: $1 / $3" /></label><label className="field">通貨 <select value={currency} disabled={Boolean(initial)} onChange={e => setCurrency(e.target.value as Currency)}>{currencies.map(c => <option key={c}>{c}</option>)}</select></label><label className="field">開始日時 <input type="datetime-local" value={startedAt} onChange={e => setStartedAt(e.target.value)} required /></label><label className="field">初回バイイン <input type="number" min="0" step="any" required value={buyIn} onChange={e => setBuyIn(e.target.value)} placeholder="300" /></label><label className="field">リバイ・追加購入 <input type="number" min="0" step="any" value={rebuy} onChange={e => setRebuy(e.target.value)} /></label></div><div className="form-divider" /><label className="toggle-row"><input type="checkbox" checked={finish} onChange={e => setFinish(e.target.checked)} /><span><strong>セッションを終了する</strong><small>キャッシュアウトを入力して収支を確定</small></span></label>{finish && <div className="form-grid"><label className="field">キャッシュアウト <input type="number" min="0" step="any" required value={cashOut} onChange={e => setCashOut(e.target.value)} placeholder="400" /></label><label className="field">チップ <input type="number" min="0" step="any" value={tips} onChange={e => setTips(e.target.value)} /></label></div>}<label className="field full">セッションメモ <textarea value={note} onChange={e => setNote(e.target.value)} rows={3} placeholder="卓の雰囲気や気づいたこと" /></label>{finish && <p className="form-hint">{rate[currency] ? `${rate[currency]?.date} 基準の参考レートで円換算します。` : 'レート未取得のため円換算は未確定です。元通貨の記録は保存できます。'}</p>}<div className="modal-actions"><button type="button" className="secondary-button" onClick={onClose}>キャンセル</button><button className="primary-button" type="submit"><Check size={17} /> 記録を保存</button></div></form></div></div>
}

function PlayerForm({ initial, onClose, onSave, onDelete }: { initial?: Player; onClose: () => void; onSave: (player: Player) => void; onDelete: (id: string) => void }) {
  const [name, setName] = useState(initial?.name || ''); const [venue, setVenue] = useState(initial?.venue || ''); const [tags, setTags] = useState(initial?.tags.join(', ') || ''); const [note, setNote] = useState(initial?.note || '')
  return <div className="modal-backdrop" onMouseDown={onClose}><div className="modal compact" onMouseDown={e => e.stopPropagation()} role="dialog" aria-modal="true" aria-label="プレイヤーメモ"><div className="modal-header"><div><div className="eyebrow">PLAYER NOTE</div><h2>{initial ? 'メモを編集' : 'プレイヤーメモ'}</h2></div><button className="icon-button" onClick={onClose} aria-label="閉じる"><X size={21} /></button></div><form onSubmit={e => { e.preventDefault(); if (!name.trim()) return; onSave({ id: initial?.id || crypto.randomUUID(), name: name.trim(), venue: venue.trim(), tags: tags.split(',').map(t => t.trim()).filter(Boolean), note: note.trim(), updatedAt: new Date().toISOString() }) }}><label className="field full">名前・仮名 <input required value={name} onChange={e => setName(e.target.value)} placeholder="例: 3番席の Michael" /></label><label className="field full">会場 <input value={venue} onChange={e => setVenue(e.target.value)} placeholder="例: Bellagio" /></label><label className="field full">タグ <input value={tags} onChange={e => setTags(e.target.value)} placeholder="タイト, 常連, アグレッシブ" /><small>カンマ区切りで入力</small></label><label className="field full">特徴・メモ <textarea rows={5} value={note} onChange={e => setNote(e.target.value)} placeholder="プレー傾向や次に覚えておきたいこと" /></label><div className="modal-actions">{initial && <button type="button" className="delete-button" onClick={() => onDelete(initial.id)}><Trash2 size={16} /> 削除</button>}<button className="primary-button" type="submit"><Check size={17} /> 保存する</button></div></form></div></div>
}

function SessionDetail({ session, currentRate, now, onClose, onEdit, onDelete, onFinish }: { session: Session; currentRate?: Rate; now: number; onClose: () => void; onEdit: () => void; onDelete: () => void; onFinish: () => void }) { const result = profit(session); const yen = asYen(result, session.currency, session.rate); const currentYen = asYen(result, session.currency, currentRate); return <div className="modal-backdrop" onMouseDown={onClose}><div className="modal detail-modal" onMouseDown={e => e.stopPropagation()} role="dialog" aria-modal="true" aria-label="セッション詳細"><div className="modal-header"><div><div className="eyebrow">SESSION DETAILS</div><h2>{session.venue}</h2><span className="detail-subtitle">{session.stakes} · {session.location || session.game} · {dateLabel((session.localDate || session.startedAt.slice(0, 10)) + 'T12:00:00')}</span></div><button className="icon-button" onClick={onClose} aria-label="閉じる"><X size={21} /></button></div><div className={`detail-result ${result < 0 ? 'loss' : ''}`}><small>{session.endedAt ? '現地通貨の収支' : '進行中のセッション'}</small><strong>{session.endedAt ? money(result, session.currency, true) : duration(session, now)}</strong><span>{session.endedAt ? `記録時の参考円換算 ${formatYen(yen, true)}` : `${money(session.buyIn + session.rebuy, session.currency)} 投入`}</span></div><div className="detail-list"><div><span>初回バイイン</span><strong>{money(session.buyIn, session.currency)}</strong></div><div><span>リバイ・追加購入</span><strong>{money(session.rebuy, session.currency)}</strong></div><div><span>キャッシュアウト</span><strong>{session.endedAt ? money(session.cashOut, session.currency) : '—'}</strong></div><div><span>チップ</span><strong>{money(session.tips, session.currency)}</strong></div><div><span>プレー時間</span><strong>{duration(session, now)}</strong></div></div>{session.rate && <div className="detail-rate"><Globe2 size={17} /><div><strong>1 {session.currency} = ¥{session.rate.rate.toFixed(2)}</strong><span>{session.rate.date} 基準 · {session.rate.provider} · 記録時に固定</span>{currentRate && currentYen !== null && yen !== null && currentYen !== yen && <span>現在の参考評価 {formatYen(currentYen, true)}（評価差 {formatYen(currentYen - yen, true)}）</span>}</div></div>}{session.note && <div className="detail-note"><Tag size={16} /><p>{session.note}</p></div>}<div className="modal-actions"><button className="delete-button" onClick={onDelete}><Trash2 size={16} /> 削除</button><button className="secondary-button" onClick={onEdit}>編集</button>{!session.endedAt && <button className="primary-button" onClick={onFinish}>終了を記録</button>}</div></div></div> }

export default App
