import { readFileSync } from 'node:fs'
import { afterAll, beforeAll, describe, it } from 'vitest'
import { initializeTestEnvironment, assertFails, assertSucceeds, type RulesTestEnvironment } from '@firebase/rules-unit-testing'
import { doc, getDoc, setDoc } from 'firebase/firestore'

let env: RulesTestEnvironment
const session = { id: 's1', venue: 'Bellagio', location: 'Las Vegas', game: 'ライブ', stakes: '$1/$3', currency: 'USD', startedAt: '2026-09-01T00:00:00Z', buyIn: 30000, rebuy: 0, cashOut: 0, tips: 0, note: '', createdAt: '2026-09-01T00:00:00Z', updatedAt: '2026-09-01T00:00:00Z' }
const trip = { id: 't1', name: 'ソウル遠征', destination: 'Seoul', startDate: '2026-09-01', endDate: '2026-09-03', expenses: [{ id: 'e1', category: '交通', amount: 4500000, currency: 'JPY', spentAt: '2026-08-01', note: '往復航空券' }], note: '', createdAt: '2026-08-01T00:00:00Z', updatedAt: '2026-08-01T00:00:00Z' }
beforeAll(async () => { env = await initializeTestEnvironment({ projectId: 'riverlog-test', firestore: { rules: readFileSync('firestore.rules', 'utf8') } }) })
afterAll(async () => { await env.cleanup() })
describe('Firestore rules', () => {
  it('allows an owner to save and read a valid session', async () => { const db = env.authenticatedContext('alice').firestore(); await assertSucceeds(setDoc(doc(db, 'users/alice/sessions/s1'), session)); await assertSucceeds(getDoc(doc(db, 'users/alice/sessions/s1'))) })
  it('denies another user and anonymous readers', async () => { await assertFails(getDoc(doc(env.authenticatedContext('bob').firestore(), 'users/alice/sessions/s1'))); await assertFails(getDoc(doc(env.unauthenticatedContext().firestore(), 'users/alice/sessions/s1'))) })
  it('denies invalid amounts and forged document IDs', async () => { const db = env.authenticatedContext('alice').firestore(); await assertFails(setDoc(doc(db, 'users/alice/sessions/s2'), { ...session, id: 's2', buyIn: -1 })); await assertFails(setDoc(doc(db, 'users/alice/sessions/s3'), session)) })
  it('accepts a trip-linked session and rejects an invalid trip reference', async () => { const db = env.authenticatedContext('alice').firestore(); await assertSucceeds(setDoc(doc(db, 'users/alice/sessions/trip-session'), { ...session, id: 'trip-session', tripId: 't1' })); await assertFails(setDoc(doc(db, 'users/alice/sessions/bad-trip'), { ...session, id: 'bad-trip', tripId: 123 })) })
  it('accepts tournament sessions and rejects invalid formats', async () => { const db = env.authenticatedContext('alice').firestore(); await assertSucceeds(setDoc(doc(db, 'users/alice/sessions/tournament'), { ...session, id: 'tournament', format: 'tournament' })); await assertFails(setDoc(doc(db, 'users/alice/sessions/bad-format'), { ...session, id: 'bad-format', format: 'sit-and-go' })) })
  it('accepts table settings and hand history, and rejects invalid seat counts', async () => { const db = env.authenticatedContext('alice').firestore(); const table = { seatCount: 9, heroSeat: 1, buttonSeat: 3, handNumber: 4, settings: { smallBlindBb: 0.5, anteBb: 0, rakePercent: 5, rakeCapBb: 3 }, players: [{ seat: 2, name: 'Alex', stackBb: 120, tags: ['タイト'], note: '' }], hands: [{ id: 'h1', number: 3, potBb: 10, rakeBb: 0.5, winnerSeats: [2], actions: [] }] }; await assertSucceeds(setDoc(doc(db, 'users/alice/sessions/table'), { ...session, id: 'table', table })); await assertFails(setDoc(doc(db, 'users/alice/sessions/bad-table'), { ...session, id: 'bad-table', table: { ...table, seatCount: 7 } })) })
  it('keeps trips private and accepts costs booked before travel', async () => { const db = env.authenticatedContext('alice').firestore(); await assertSucceeds(setDoc(doc(db, 'users/alice/trips/t1'), trip)); await assertSucceeds(getDoc(doc(db, 'users/alice/trips/t1'))); await assertFails(getDoc(doc(env.authenticatedContext('bob').firestore(), 'users/alice/trips/t1'))) })
  it('denies an invalid trip range and forged trip IDs', async () => { const db = env.authenticatedContext('alice').firestore(); await assertFails(setDoc(doc(db, 'users/alice/trips/t2'), { ...trip, id: 't2', startDate: '2026-09-04', endDate: '2026-09-03' })); await assertFails(setDoc(doc(db, 'users/alice/trips/t3'), trip)) })
})
